---
- name: include lvm tasks
  include: lvm.yml
  when: lvm
  tags: docker

- name: ensure extras satellite channel is available
  command: yum repolist
  register: repos
  failed_when: '"extras" not in repos.stdout'
  changed_when: false
  tags: docker

- name: make sure docker is installed
  yum:
    name: 'docker-{{ docker_version }}'
    state: present
  notify: restart docker
  tags: docker

- name: configure docker
  template:
    src: docker.j2
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: 0644
  notify: restart docker
  tags: docker

- name: exectue now all triggered handlers
  meta: flush_handlers
  tags: docker

- name: make sure docker is started
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: install docker-compose
  template:
    src: docker-compose.j2
    dest: '{{ docker_compose_path }}'
    owner: root
    group: root
    mode: 0750
  tags: docker
